site_name: where-for-dinner
site_description: A Microservice Reference Application for Tanzu Application Platform
site_author: user:ben.wilcock
nav:
  - About: index.md
plugins:
  - techdocs-core
metadata:
  namespace: default
kind: system
