# This is used to build the TechDocs for this component and is referenced here: https://github.com/benwilcock/backstage-catalogs/blob/main/system-wheres-for-dinner.yml
site_name: 'where-for-dinner'
site_description: 'A Spring Boot sample built using Maven'
site_author: user:greg.meyer

nav:
  - About: 'index.md'