site_name: tanzu-application-platform
site_description: Tanzu Application Platform
site_author: user:ben.wilcock
nav:
  - 'Introduction': index.md
  - 'Use Cases': usecases.md
  # - 'Getting Started (Ops)': get-started-ops.md
  - 'Getting Started (Dev)': get-started-devs.md
  # - 'How It Works': how-it-works.md
  # - 'System Architecture': architecture.md
  - 'Tanzu CLI': tanzu-cli.md
  - 'Tanzu IDE Plugins': ide-plugins.md
  - 'Tanzu Learning Centers': learning-centers.md
  - 'Tanzu Developer Portal': developer-portal.md
  - 'Application Accelerators': accelerators.md
  - 'Getting Help': help.md
plugins:
  - techdocs-core
metadata:
  namespace: default
kind: system