site_name: tanzu-application-platform
site_description: Tanzu Application Platform
site_author: user:ben.wilcock
nav:
  - 'Introduction': index.md
  - 'Overview': overview.md
  - 'Use Cases': usecases.md
  - 'Getting Help': help.md
  # - 'Getting Started (Platform Operators)': get-started-ops.md
  # - 'Getting Started (Application Developers)': get-started-devs.md
  # - 'How It Works': how-it-works.md
  # - 'System Architecture': architecture.md
  # - 'The Tanzu CLI': tanzu-cli.md
  # - 'Application Accelerators': accelerators.md
plugins:
  - techdocs-core
metadata:
  namespace: default
kind: system