site_name: tanzu-application-platform
site_description: Tanzu Application Platform
site_author: user:ben.wilcock
nav:
  - 'Introduction': index.md
  - 'Use Cases': usecases.md
  # - 'Getting Started (Ops)': get-started-ops.md
  - 'Getting Started': get-started-devs.md
  # - 'How It Works': how-it-works.md
  - 'System Architecture': architecture.md
  - 'Tanzu CLI': tanzu-cli.md
  - 'Tanzu IDE Plugins': ide-plugins.md
  - 'Tanzu Developer Portal': tanzu-developer-portal.md
  - 'Tanzu Learning Centers': learning-centers.md
  - 'Application Accelerators': accelerators.md
  - 'Developer APIs': developer-apis.md
  - 'Getting Help': help.md

plugins:
  - techdocs-core
metadata:
  namespace: default
kind: system